[package]
name = "hpx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
crossterm = "0.28.1"
libbpf-rs = "0.24.5"
pnet = "0.35.0"
ratatui = "0.28.1"
rlimit = "0.10.2"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
