[package]
name = "hpx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
libbpf-rs = "0.24.5"
pnet = "0.35.0"
rlimit = "0.10.2"
tokio = { version = "1.40.0", features = ["full"] }

[build-dependencies]
cc = "1.1.28"
